# Generated by Django 4.1.2 on 2022-10-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('smiles', models.CharField(max_length=256)),
                ('citation', models.URLField()),
                ('e_sigma', models.FloatField()),
                ('e_pi', models.FloatField()),
            ],
        ),
    ]
